# Generated by deployment-features/k8s/litellm/terraform/module

nameOverride: ${name}
fullnameOverride: ${name}

replicaCount: ${replica_count}

image:
  repository: ${image_repository}
  tag: ${image_tag}
  pullPolicy: ${image_pull_policy}

serviceAccount:
  create: true
  name: ${name}
  annotations:
${service_account_annotations_yaml}

deploymentLabels:
${labels_yaml}

podLabels:
${labels_yaml}

db:
  useExisting: true
  deployStandalone: false
  endpoint: ${database_endpoint}
  database: ${database_name}
  secret:
    name: ${database_secret_name}
    usernameKey: username
    passwordKey: ${database_secret_password_key}

masterkeySecretName: ${master_key_secret_name}
masterkeySecretKey: ${master_key_secret_key}

proxyConfigMap:
  create: true

proxy_config:
${proxy_config_yaml}

logLevel: ${litellm_log_level}

envVars:
  AWS_REGION: ${aws_region}
  AWS_DEFAULT_REGION: ${aws_region}
  LITELLM_MODE: PRODUCTION
  LITELLM_COST_FOOTER: "${litellm_cost_footer ? "1" : "0"}"
  LITELLM_PROMPT_CACHE: "${litellm_prompt_cache ? "1" : "0"}"
  UI_USERNAME: ${ui_username}

extraEnvVars:
  - name: UI_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ${ui_password_secret_name}
        key: ${ui_password_secret_key}

migrationJob:
  enabled: true
  hooks:
    argocd:
      enabled: true
    helm:
      enabled: true

ingress:
  enabled: ${ingress_enabled}
  className: ${ingress_class_name}
  hosts:
    - host: ${ingress_host}
      paths:
        - path: /
          pathType: Prefix
%{ if ingress_tls_secret_name != "" ~}
  tls:
    - secretName: ${ingress_tls_secret_name}
      hosts:
        - ${ingress_host}
%{ endif ~}

%{ if cache_persistence_enabled ~}
volumes:
  - name: litellm-cache
    persistentVolumeClaim:
      claimName: ${name}-cache

volumeMounts:
  - name: litellm-cache
    mountPath: /app/.litellm_cache
%{ endif ~}

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 2Gi

livenessProbe:
  path: /health/liveliness
  initialDelaySeconds: 30
  periodSeconds: 15

readinessProbe:
  path: /health/readiness
  initialDelaySeconds: 20
  periodSeconds: 10

startupProbe:
  path: /health/readiness
  failureThreshold: 30
  periodSeconds: 10

autoscaling:
  enabled: false

redis:
  enabled: false

postgresql:
  auth:
    username: ${database_username}
    database: ${database_name}
